name: WorldChatFormats
main: com.lgdxcompany.worldchatformats.chat_formater_addon_for_chatmanger
version: 1.0
api-version: 1.20
description: Custom chat formatter for specific worlds
author: AhmedLegend
depend: [PlaceholderAPI,LuckPerms,Vault]
softdepend: [Multiverse-Core, PlaceholderAPI, ChatManager, DeluxeMenus, Vault, Bedwars1058, PerWorldPlugins, HolographicDisplays, SuperVanish, ViaVersion, ViaBackwards, ViaRewind, LilyPad-Connect, LuckPerms]
commands:
  worldchatformat:
    description: "Main command for chat formatting"
    usage: "/worldchatformat <reload|toggleDefaultChatFormat|toggleWorldChatFormat|toggleGroupRankFormat>"
    default: op
  wcf:
    description: "Alias for worldchatformat"
    usage: "/wcf <reload|toggleDefaultChatFormat|toggleWorldChatFormat|toggleGroupRankFormat>"
    default: op
  toggleDefaultChatFormat:
    description: "Toggles default chat format"
    usage: "/toggleDefaultChatFormat"
    permission: worldchatformat.toggle
    permission-message: You do not have permission to toggle visibility.
  toggleWorldChatFormat:
    description: "Toggles world chat format"
    usage: "/toggleWorldChatFormat"
    permission: worldchatformat.toggle
    permission-message: You do not have permission to toggle visibility.
  toggleGroupRankFormat:
    description: "Toggles group rank format"
    usage: "/toggleGroupRankFormat"
    permission: worldchatformat.toggle
    permission-message: You do not have permission to toggle visibility.
